# Generated by Django 5.0.3 on 2024-04-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=32, null=True)),
                ('fechaFin', models.CharField(blank=True, max_length=32, null=True)),
                ('estadoTarea', models.CharField(blank=True, max_length=32, null=True)),
                ('responsableTarea', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
